var search={
  "<Generic Classes>": "https://archaeolink.github.io/n4o-ta4-conservation/Generic",
  "AnnotationProperty Instances Collection": "https://archaeolink.github.io/n4o-ta4-conservation/AnnotationProperty_collection",
  "Class Instances Collection": "https://archaeolink.github.io/n4o-ta4-conservation/Class_collection",
  "Eingriff": "https://archaeolink.github.io/n4o-ta4-conservation/dYxXkaqsnBqVYA1THAxjgE",
  "LEIZA Restaurierungs- und Konserverungsthesaurus": "https://archaeolink.github.io/n4o-ta4-conservation/",
  "LEIZA Restaurierungs- und Konservierungsthesaurus": "https://archaeolink.github.io/n4o-ta4-conservation/LEIZA_Conservation_Thesaurus",
  "Label Instances Collection": "https://archaeolink.github.io/n4o-ta4-conservation/Label_collection",
  "Material": "https://archaeolink.github.io/n4o-ta4-conservation/wsbDppTfr2BSxsmhSuEbG4",
  "Metall": "https://archaeolink.github.io/n4o-ta4-conservation/2dmdnWjmWJURKh9PLaJuH1",
  "Methode und Technik": "https://archaeolink.github.io/n4o-ta4-conservation/tmjVdStfYu6PQuQeq7Sua7",
  "NamedIndividual Instances Collection": "https://archaeolink.github.io/n4o-ta4-conservation/NamedIndividual_collection",
  "Ontology Instances Collection": "https://archaeolink.github.io/n4o-ta4-conservation/Ontology_collection",
  "Organik": "https://archaeolink.github.io/n4o-ta4-conservation/sSygVCh1KaCSrkS5Ku3Aak",
  "Restaurierung": "https://archaeolink.github.io/n4o-ta4-conservation/6jF9fBDq7W2tyRHLj554AT",
  "Silikat": "https://archaeolink.github.io/n4o-ta4-conservation/1eo1EwnxCPF6yukEJo1Wdq",
  "Vocabulary Instances Collection": "https://archaeolink.github.io/n4o-ta4-conservation/Vocabulary_collection",
  "Werkzeug": "https://archaeolink.github.io/n4o-ta4-conservation/3EE7pLjByXiT4nHWxyqKuB",
  "Zustandserfassung": "https://archaeolink.github.io/n4o-ta4-conservation/eq7GtLWHJesucfazgADPZE",
  "[Diagnose]": "https://archaeolink.github.io/n4o-ta4-conservation/qfYhqzHDc8FTxu1A6T6ycW",
  "[Objekt-Werkstoff]": "https://archaeolink.github.io/n4o-ta4-conservation/8kKtpbqpnY2T2k7EixxdoP",
  "[Objektuntersuchung]": "https://archaeolink.github.io/n4o-ta4-conservation/stStRVHTWT8PXV2Lj19GGL",
  "[Restaurierungs-/ Konservierungsplanung]": "https://archaeolink.github.io/n4o-ta4-conservation/cpT73gbyUgA22vohdo4rUa",
  "has source": "https://archaeolink.github.io/n4o-ta4-conservation/hasSource",
  "hat Quelle": "https://archaeolink.github.io/n4o-ta4-conservation/hasSource",
  "stabilisierende Konservierung": "https://archaeolink.github.io/n4o-ta4-conservation/wF7jn2tBfcnE3drqjzwi8D"
}