var search={
  "<Generic Classes>": "https://archaeolink.github.io/n4o-ta4-conservation/Generic",
  "Actor": "https://archaeolink.github.io/n4o-ta4-conservation/Actor",
  "Akteur": "https://archaeolink.github.io/n4o-ta4-conservation/Actor",
  "AnnotationProperty Instances Collection": "https://archaeolink.github.io/n4o-ta4-conservation/AnnotationProperty_collection",
  "Begriff": "https://archaeolink.github.io/n4o-ta4-conservation/Label",
  "Beschreibung": "https://archaeolink.github.io/n4o-ta4-conservation/description",
  "Class Instances Collection": "https://archaeolink.github.io/n4o-ta4-conservation/Class_collection",
  "Datatype Instances Collection": "https://archaeolink.github.io/n4o-ta4-conservation/Datatype_collection",
  "LEIZA Restaurierungs- und Konserverungsthesaurus": "https://archaeolink.github.io/n4o-ta4-conservation/LEIZA_Conservation_Thesaurus",
  "Label": "https://archaeolink.github.io/n4o-ta4-conservation/Label",
  "NamedIndividual Instances Collection": "https://archaeolink.github.io/n4o-ta4-conservation/NamedIndividual_collection",
  "Ontology Instances Collection": "https://archaeolink.github.io/n4o-ta4-conservation/Ontology_collection",
  "Quelle": "https://archaeolink.github.io/n4o-ta4-conservation/Source",
  "Source": "https://archaeolink.github.io/n4o-ta4-conservation/Source",
  "Structural Concept": "https://archaeolink.github.io/n4o-ta4-conservation/StructualConcept",
  "Vocabulary": "https://archaeolink.github.io/n4o-ta4-conservation/Vocabulary",
  "Vocabulary Instances Collection": "https://archaeolink.github.io/n4o-ta4-conservation/Vocabulary_collection",
  "Vokabular": "https://archaeolink.github.io/n4o-ta4-conservation/Vocabulary",
  "Vokabular Beschreibung": "https://archaeolink.github.io/n4o-ta4-conservation/vocabularyDescription",
  "Vokabular Identifier": "https://archaeolink.github.io/n4o-ta4-conservation/vocabularyIdentifier",
  "Vokabular Sprache": "https://archaeolink.github.io/n4o-ta4-conservation/vocabularyLanguage",
  "Vokabular Titlel": "https://archaeolink.github.io/n4o-ta4-conservation/vocabularyTitle",
  "alternative label": "https://archaeolink.github.io/n4o-ta4-conservation/alternativeLabel",
  "alternativer Bezeichner": "https://archaeolink.github.io/n4o-ta4-conservation/alternativeLabel",
  "description": "https://archaeolink.github.io/n4o-ta4-conservation/description",
  "has related label": "https://archaeolink.github.io/n4o-ta4-conservation/hasRelatedLabel",
  "has sub label": "https://archaeolink.github.io/n4o-ta4-conservation/hasSubLabel",
  "has super label": "https://archaeolink.github.io/n4o-ta4-conservation/hasSuperLabel",
  "hat Mutter-Bezeichner": "https://archaeolink.github.io/n4o-ta4-conservation/hasSuperLabel",
  "hat Tochter-Bezeichner": "https://archaeolink.github.io/n4o-ta4-conservation/hasSubLabel",
  "hat related Bezeichner": "https://archaeolink.github.io/n4o-ta4-conservation/hasRelatedLabel",
  "identifier": "https://archaeolink.github.io/n4o-ta4-conservation/identifier",
  "identifier label": "https://archaeolink.github.io/n4o-ta4-conservation/identifierLabel",
  "pr\u00e4ferierter Bezeichner": "https://archaeolink.github.io/n4o-ta4-conservation/identifierLabel",
  "translation": "https://archaeolink.github.io/n4o-ta4-conservation/translation",
  "vocabulary creator string": "https://archaeolink.github.io/n4o-ta4-conservation/vocabularyCreatorString",
  "vocabulary description": "https://archaeolink.github.io/n4o-ta4-conservation/vocabularyDescription",
  "vocabulary identifier": "https://archaeolink.github.io/n4o-ta4-conservation/vocabularyIdentifier",
  "vocabulary language": "https://archaeolink.github.io/n4o-ta4-conservation/vocabularyLanguage",
  "vocabulary license string": "https://archaeolink.github.io/n4o-ta4-conservation/vocabularyLicenseString",
  "vocabulary title": "https://archaeolink.github.io/n4o-ta4-conservation/vocabularyTitle",
  "\u00dcbersetzung": "https://archaeolink.github.io/n4o-ta4-conservation/translation"
}